### ISSUE TITLE
TECH: Huistijl voorzien (default/werkbaar)

### ISSUE THREAD

**Issue by Bumbolt** [Bumbolt/redo-air#16]
index.html  met frame. 

header
sidenav
loginform
footer

Iedere andere view heeft zijn eigen .html file en zal gerendered worden binnen de ui-component / pagecontent

Afgesproken : PrimeFaces

**Comment by FrederikV** [comment]
Added dependency and repository to pom.xml

**Comment by Bumbolt** [comment]
rechtermuis op `web-module` > `Add frameworksupport...` > `PrimeFaces`  kan handig zijn.

**Comment by nicolasquartier** [comment]
ideetje om 404-page toe te voegen.

**Comment by nicolasquartier** [comment]
change config zodat 404-page default page-not-found page is

**Comment by Bumbolt** [comment]
TEST: Is ok.

Nieuw ticket voorzien voor navigatie aan te maken & pagecontent te alignen
