### ISSUE TITLE
Als User wil ik kunnen registeren en mijn account kunnen beheren

### ISSUE THREAD

**Issue by Bumbolt** [Bumbolt/redo-air#4]
UserService
   - CRUD

E-mail confirmatie to analyse op ander ticket #19

**Comment by nicolasquartier** [comment]
@TODO: add e-mail regex
@TODO: hash passwoord vooraleer het in de db te steken

**Comment by nicolasquartier** [comment]
- [x] add e-mail regex
- [x]  hash passwoord vooraleer het in de db te steken

**Comment by nicolasquartier** [comment]
Als user moet ik eerst kunnen inloggen, vooraleer ik mijn account kan beheren

**Comment by nicolasquartier** [comment]
- [X] Als user moet ik eerst kunnen inloggen, vooraleer ik mijn account kan beheren

**Comment by nicolasquartier** [comment]
@TODO: TESTEEN!!

**Comment by Bumbolt** [comment]
Userdetails nog aangepast in 2117be1 zodat er een foutboodschap gegeven wordt bij fout oud wachtwoord.
